# Generated by Django 6.0 on 2025-12-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subdomain name', max_length=100, unique=True)),
                ('odoo_version', models.CharField(choices=[('14.0', '14.0'), ('15.0', '15.0'), ('16.0', '16.0'), ('17.0', '17.0')], default='17.0', max_length=10)),
                ('status', models.CharField(choices=[('deploying', 'Deploying'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='deploying', max_length=20)),
                ('github_repo', models.CharField(blank=True, max_length=255, null=True)),
                ('github_branch', models.CharField(default='main', max_length=100)),
                ('container_id', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
