# Generated by Django 6.0 on 2025-12-29 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_access_token', models.CharField(blank=True, help_text='GitHub Personal Access Token', max_length=255)),
                ('default_organization', models.CharField(blank=True, help_text='Default GitHub organization', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook secret for GitHub', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Configuration',
                'verbose_name_plural': 'GitHub Configurations',
            },
        ),
    ]
