# Generated by Django 6.0 on 2025-12-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0003_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconfig',
            name='registration_enabled',
            field=models.BooleanField(default=True, help_text='Allow new user registrations'),
        ),
    ]
