# Generated by Django 6.0 on 2025-12-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0005_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconfig',
            name='main_domain',
            field=models.CharField(blank=True, help_text='Main domain for the application (e.g., example.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='githubconfig',
            name='ssl_certificate_path',
            field=models.CharField(blank=True, help_text='Path to SSL certificate file', max_length=500),
        ),
        migrations.AddField(
            model_name='githubconfig',
            name='ssl_enabled',
            field=models.BooleanField(default=False, help_text='Enable SSL/HTTPS for the domain'),
        ),
        migrations.AddField(
            model_name='githubconfig',
            name='ssl_key_path',
            field=models.CharField(blank=True, help_text='Path to SSL private key file', max_length=500),
        ),
    ]
