# Generated by Django 6.0 on 2025-12-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0006_githubconfig_main_domain_and_more'),
    ]

    operations = [
    ]
