# Generated by Django 6.0 on 2025-12-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Custom domain (e.g., ejemplo.com)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='ssl_certificate_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='ssl_email',
            field=models.EmailField(blank=True, help_text="Email for Let's Encrypt notifications", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='ssl_enabled',
            field=models.BooleanField(default=False, help_text='SSL/HTTPS enabled'),
        ),
        migrations.AddField(
            model_name='instance',
            name='ssl_key_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='odoo_version',
            field=models.CharField(choices=[('10.0', '10.0'), ('11.0', '11.0'), ('12.0', '12.0'), ('13.0', '13.0'), ('14.0', '14.0'), ('15.0', '15.0'), ('16.0', '16.0'), ('17.0', '17.0'), ('18.0', '18.0'), ('19.0', '19.0')], default='17.0', max_length=10),
        ),
    ]
