# Generated by Django 6.0 on 2025-12-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0009_instance_custom_domain_instance_ssl_certificate_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconfig',
            name='auto_backup_frequency',
            field=models.CharField(choices=[('none', 'Disabled'), ('hourly', 'Every Hour'), ('daily', 'Every Day'), ('weekly', 'Every Week')], default='none', help_text='Frequency of automatic backups', max_length=20),
        ),
        migrations.AddField(
            model_name='githubconfig',
            name='auto_backup_retention',
            field=models.IntegerField(default=5, help_text='Number of backups to keep'),
        ),
    ]
