# Generated by Django 6.0 on 2025-12-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0010_githubconfig_auto_backup_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubconfig',
            name='auto_backup_frequency',
            field=models.CharField(choices=[('none', 'Disabled'), ('minutes', 'Every 5 Minutes'), ('hourly', 'Every Hour'), ('daily', 'Every Day'), ('weekly', 'Every Week')], default='none', help_text='Frequency of automatic backups', max_length=20),
        ),
    ]
