# Generated by Django 6.0 on 2025-12-31 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0011_alter_githubconfig_auto_backup_frequency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('template', models.CharField(choices=[('custom', 'Custom'), ('n8n', 'n8n - Workflow Automation'), ('pgadmin', 'pgAdmin - PostgreSQL Admin'), ('portainer', 'Portainer - Docker Management'), ('redis', 'Redis - Cache Database'), ('mongodb', 'MongoDB - NoSQL Database')], default='custom', max_length=50)),
                ('image', models.CharField(help_text='Docker image (e.g., n8nio/n8n:latest)', max_length=255)),
                ('port', models.IntegerField(help_text='Host port to expose')),
                ('container_port', models.IntegerField(help_text='Container internal port')),
                ('environment', models.JSONField(blank=True, default=dict, help_text='Environment variables')),
                ('volumes', models.JSONField(blank=True, default=dict, help_text='Volume mappings')),
                ('network', models.CharField(blank=True, default='bridge', max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error'), ('creating', 'Creating')], default='stopped', max_length=20)),
                ('container_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
                'ordering': ['-created_at'],
            },
        ),
    ]
