# Generated by Django 6.0 on 2025-12-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0012_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Enable two-factor authentication'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_secret',
            field=models.CharField(blank=True, help_text='TOTP secret key', max_length=32),
        ),
    ]
