# Generated by Django 6.0 on 2025-12-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0013_userprofile_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconfig',
            name='public_website_enabled',
            field=models.BooleanField(default=True, help_text='Enable standard public website (Home, Blog, etc.)'),
        ),
    ]
