# Generated by Django 6.0 on 2025-12-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0014_githubconfig_public_website_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubconfig',
            name='auto_backup_retention',
        ),
        migrations.AlterField(
            model_name='githubconfig',
            name='auto_backup_frequency',
            field=models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='never', max_length=20),
        ),
        migrations.AlterField(
            model_name='githubconfig',
            name='public_website_enabled',
            field=models.BooleanField(default=False, help_text='Enable public website for the platform'),
        ),
        migrations.DeleteModel(
            name='Container',
        ),
    ]
