# Generated by Django 6.0 on 2025-12-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0016_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconfig',
            name='auto_backup_retention',
            field=models.IntegerField(default=5, help_text='Number of backups to keep per instance'),
        ),
        migrations.AlterField(
            model_name='githubconfig',
            name='auto_backup_frequency',
            field=models.CharField(choices=[('none', 'Disabled'), ('minutes', 'Every 5 Minutes'), ('hourly', 'Every Hour'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20),
        ),
    ]
