# Generated by Django 6.0 on 2025-12-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0017_githubconfig_auto_backup_retention_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubconfig',
            name='auto_backup_frequency',
        ),
        migrations.RemoveField(
            model_name='githubconfig',
            name='auto_backup_retention',
        ),
        migrations.RemoveField(
            model_name='githubconfig',
            name='public_website_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_secret',
        ),
        migrations.AddField(
            model_name='instance',
            name='database_name',
            field=models.CharField(blank=True, help_text='Nombre de la base de datos de Odoo (dejar vacío para auto-detección)', max_length=100, null=True),
        ),
    ]
