# Generated by Django 6.0 on 2025-12-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0018_remove_githubconfig_auto_backup_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconfig',
            name='public_website_enabled',
            field=models.BooleanField(default=True, help_text='Enable public website and blog'),
        ),
    ]
