# Generated by Django 6.0 on 2025-12-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0019_githubconfig_public_website_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconfig',
            name='two_factor_required',
            field=models.BooleanField(default=False, help_text='Require two-factor authentication for all users'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Enable two-factor authentication'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_secret',
            field=models.CharField(blank=True, help_text='TOTP secret key', max_length=32),
        ),
    ]
