# Generated by Django 6.0 on 2025-12-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0020_githubconfig_two_factor_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='origin',
            field=models.CharField(blank=True, help_text='Origin of instance creation (manual, backup, duplicate)', max_length=50, null=True),
        ),
    ]
