# Generated by Django 6.0 on 2025-12-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0021_instance_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconfig',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Enable email notifications for instance operations'),
        ),
        migrations.AddField(
            model_name='githubconfig',
            name='notification_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of emails to receive notifications'),
        ),
    ]
