# Generated by Django 6.0 on 2025-12-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0022_githubconfig_email_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconfig',
            name='auto_backup_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic backups for all instances'),
        ),
        migrations.AddField(
            model_name='githubconfig',
            name='auto_backup_frequency_unit',
            field=models.CharField(choices=[('minute', 'Minutos'), ('hour', 'Horas'), ('day', 'Días'), ('week', 'Semanas')], default='day', help_text='Unit of time for backup frequency', max_length=10),
        ),
        migrations.AddField(
            model_name='githubconfig',
            name='auto_backup_frequency_value',
            field=models.IntegerField(default=5, help_text='How often to run backups (e.g., every 5 days)'),
        ),
        migrations.AddField(
            model_name='githubconfig',
            name='auto_backup_retention',
            field=models.IntegerField(default=5, help_text='Number of backups to keep. Older backups will be deleted automatically'),
        ),
    ]
