# Generated by Django 6.0 on 2025-12-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0023_githubconfig_auto_backup_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='security_password',
            field=models.CharField(blank=True, help_text='Contraseña de seguridad para borrado', max_length=100, null=True),
        ),
    ]
