# Generated by Django 6.0 on 2025-12-31 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0024_instance_security_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.CharField(help_text='URL del repositorio (https://github.com/user/repo)', max_length=255)),
                ('branch', models.CharField(default='main', help_text='Rama a utilizar (ej. main, 14.0, master)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_repositories', to='orchestrator.instance')),
            ],
        ),
    ]
