# Generated by Django 6.0 on 2025-12-31 20:11

import orchestrator.container_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0025_instancerepository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='security_password',
        ),
        migrations.AddField(
            model_name='container',
            name='command',
            field=models.CharField(blank=True, help_text='Custom command to run', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='template',
            field=models.CharField(choices=orchestrator.container_models.get_template_choices, default='custom', max_length=50),
        ),
        migrations.DeleteModel(
            name='InstanceRepository',
        ),
    ]
