# Generated by Django 6.0 on 2026-01-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0026_remove_instance_security_password_container_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Custom domain for this container', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='ssl_certificate_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='ssl_email',
            field=models.EmailField(blank=True, help_text="Email for Let's Encrypt", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='ssl_enabled',
            field=models.BooleanField(default=False, help_text='Enable SSL/HTTPS'),
        ),
        migrations.AddField(
            model_name='container',
            name='ssl_key_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
