http:
  routers:
    instance-odoo19:
      entryPoints:
      - web
      priority: 100
      rule: Host(`communitysh.xyz`)
      service: instance-odoo19-service
  services:
    instance-odoo19-service:
      loadBalancer:
        servers:
        - url: http://172.18.0.1:None
