http:
  routers:
    app-localhost:
      rule: "Host(`localhost`)"
      entryPoints:
        - web
      service: app-localhost-service
      priority: 1
  
  services:
    app-localhost-service:
      loadBalancer:
        servers:
          - url: "http://app:8000"
